---
- name: Disable root login over SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
  notify: Restart SSH

- name: Set UFW rules
  ufw:
    rule: allow
    name: "Apache Full"

- name: Enable UFW
  ufw:
    state: enabled
